apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-validadorcpf-dev
spec:
  type: NodePort
  selector:
    app: label-pod-validadorcpf-dev
  ports:
    - port: 8083
      nodePort: 30013 #até 32767