apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-validadorcpf-prod
spec:
  type: NodePort
  selector:
    app: label-pod-validadorcpf-prod
  ports:
    - port: 8081
      nodePort: 30012 #até 32767