apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-validadorcpf-qa
spec:
  type: NodePort
  selector:
    app: label-pod-validadorcpf-qa
  ports:
    - port: 8081
      nodePort: 30011 #até 32767